apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: cep-project1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - hard
volumeBindingMode: Immediate
